apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: hello-world
        image: sankarsenthil002/helloworld
        ports:
        - containerPort: 80        